<?xml version="1.0" encoding="utf-8"?><Database Name="2-sem-gr-1" Class="ITExpressDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ucl-jtm-sqlserver.database.windows.net;Initial Catalog=2-sem-gr-1;Persist Security Info=True;User ID=2-sem-gr-1-login" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="_2_sem_gr_1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Admin_UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Admin_Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Specialization" Member="Specializations">
    <Type Name="Specialization">
      <Column Name="Specialization_CodeLanguage" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Specialization_EndType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Specialization_Description" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Specialization_ConsultantId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Consultant_Specialization" Member="Consultant" ThisKey="Specialization_ConsultantId" OtherKey="ConsultantId" Type="Consultant" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Consultant" Member="Consultants">
    <Type Name="Consultant">
      <Column Name="ConsultantId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Consultant_FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Consultant_LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Consultant_Login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Consultant_Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Consultant_Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Consultant_ZipCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Consultant_City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Consultant_Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Consultant_PhoneNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Consultant_Specialization" Member="Specializations" ThisKey="ConsultantId" OtherKey="Specialization_ConsultantId" Type="Specialization" />
      <Association Name="Consultant_Invitation" Member="Invitations" ThisKey="ConsultantId" OtherKey="Invitaiton_ConsultantId" Type="Invitation" />
      <Association Name="Consultant_Message" Member="Messages" ThisKey="ConsultantId" OtherKey="Message_ConsultantId" Type="Message" />
      <Association Name="Consultant_Project" Member="Projects" ThisKey="ConsultantId" OtherKey="Project_ConsultantId" Type="Project" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Customer_FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Customer_LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Customer_Login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Customer_Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Customer_Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Customer_ZipCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Customer_City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Customer_Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Customer_PhoneNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Invitation" Member="Invitations" ThisKey="CustomerId" OtherKey="Invitation_CustomerId" Type="Invitation" />
      <Association Name="Customer_Message" Member="Messages" ThisKey="CustomerId" OtherKey="Message_CustomerId" Type="Message" />
      <Association Name="Customer_Project" Member="Projects" ThisKey="CustomerId" OtherKey="Project_CustomerId" Type="Project" />
    </Type>
  </Table>
  <Table Name="dbo.Invitation" Member="Invitations">
    <Type Name="Invitation">
      <Column Name="InvitationId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Invitation_Content" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Invitation_CustomerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Invitaiton_ConsultantId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Invitation" Member="Customer" ThisKey="Invitation_CustomerId" OtherKey="CustomerId" Type="Customer" IsForeignKey="true" />
      <Association Name="Consultant_Invitation" Member="Consultant" ThisKey="Invitaiton_ConsultantId" OtherKey="ConsultantId" Type="Consultant" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Message" Member="Messages">
    <Type Name="Message">
      <Column Name="MessageId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Message_content" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Message_CustomerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Message_ConsultantId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Message" Member="Customer" ThisKey="Message_CustomerId" OtherKey="CustomerId" Type="Customer" IsForeignKey="true" />
      <Association Name="Consultant_Message" Member="Consultant" ThisKey="Message_ConsultantId" OtherKey="ConsultantId" Type="Consultant" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Project" Member="Projects">
    <Type Name="Project">
      <Column Name="ProjectId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Project_Description" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Project_Requirements" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Project_TotalSum" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Project_HourWage" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Project_StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Project_EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Project_TimeUsed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Project_Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Project_CustomerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Project_ConsultantId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Project" Member="Customer" ThisKey="Project_CustomerId" OtherKey="CustomerId" Type="Customer" IsForeignKey="true" />
      <Association Name="Consultant_Project" Member="Consultant" ThisKey="Project_ConsultantId" OtherKey="ConsultantId" Type="Consultant" IsForeignKey="true" />
    </Type>
  </Table>
</Database>